services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:3000"
    networks:
      - backend

  user-service:
    build: ./user-service
    ports:
      - "4002:3000"
    networks:
      - backend
    depends_on:
      - mongo
    volumes:
      - /home/borjaeditions/servicios_b/panel_minecraft/uploads

  world-service:
    build: ./world-service
    ports:
      - "4003:3000"
    networks:
      - backend
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./world-service/.env

  api-gateway:
    build: ./api-gateway
    ports:
      - "4001:3000"
    networks:
      - backend
    depends_on:
      - auth-service
      - user-service
      - world-service

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
